from __future__ import annotations

import re
from datetime import date

from .models import Item, Summary
from .textutil import TWEET_LIMIT, truncate, tweet_length


def render_markdown(day: date, entries: list[tuple[Item, Summary]], summarizer_name: str) -> str:
    lines = [f"# AI Agents & AI News Digest - {day.isoformat()}", "",
             f"*Top {len(entries)} items, deduped and ranked. Summarizer: `{summarizer_name}`.*", ""]
    for n, (item, s) in enumerate(entries, 1):
        extra = f" (also: {', '.join(item.also_seen_in)})" if item.also_seen_in else ""
        meta = f"{item.source}{extra}"
        if item.points:
            meta += f" | {item.points} pts, {item.comments} comments"
        lines += [f"## {n}. [{item.title}]({item.url})", f"*{meta}*", "",
                  s.summary, "", f"**So what:** {s.so_what}", ""]
    return "\n".join(lines).rstrip() + "\n"


def _fit(prefix: str, body: str, suffix: str) -> str:
    """Build prefix+body+suffix, truncating body so the tweet is <= 280."""
    room = TWEET_LIMIT - tweet_length(prefix + suffix)
    # body has no URLs, so len == tweet_length
    return prefix + truncate(body, max(room, 20)) + suffix


def render_thread(day: date, entries: list[tuple[Item, Summary]], max_items: int = 5,
                  repo_url: str = "") -> list[str]:
    """Tweet thread: hook first, one item per tweet, closing CTA. Each <= 280."""
    picks = entries[:max_items]
    if not picks:
        return []
    top = picks[0][0]
    hook = _fit("", f"AI agents + AI news, {day.strftime('%b')} {day.day}: the {len(picks)} things worth "
                    f"your time, each with a so-what. Lead story: {top.title}", " \U0001F9F5")
    tweets = [hook]
    total = len(picks) + 2
    for n, (item, s) in enumerate(picks, 1):
        prefix = f"{n}/ "
        suffix = f"\n\n{item.url}"
        head = truncate(item.title, 110)
        so_what = re.sub(r"\s*Covered by \d+ sources.*$", "", s.so_what)  # keep tweets tight
        body = f"{head}\n\nSo what: {so_what}"
        tweets.append(_fit(prefix, body, suffix))
    closing = "That is the digest. Generated by an open-source agent that reads feeds, dedupes, ranks, and adds a take."
    if repo_url:
        closing += f"\n\nCode: {repo_url}"
    closing += "\n\nFollow for a daily one."
    tweets.append(_fit("", closing, "") if tweet_length(closing) > TWEET_LIMIT else closing)
    # number the hook
    tweets[0] = tweets[0] if tweet_length(tweets[0]) <= TWEET_LIMIT else truncate(tweets[0], TWEET_LIMIT)
    return tweets


def format_thread(tweets: list[str]) -> str:
    out = []
    for n, t in enumerate(tweets, 1):
        out.append(f"--- Tweet {n}/{len(tweets)} ({tweet_length(t)} chars) ---\n{t}\n")
    return "\n".join(out)
